# Building a GPT

This is the [GitHub Repository](https://github.com/NeviduJ/ICTer-Workshop-Transformers) which includes all the materials we will use today.

Special thanks to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT by Andrej Karparthy.

## Load Dataset and Explore

In [1]:
FILE_ID = '1N8WEfNQhlBa2MFAXWz4JuvIo3daEnPwZ'
OUTPUT_FILENAME = 'sinhala_raw_data.txt'

# Use gdown to download the file directly using the ID
# -O: specifies the output filename
!gdown --id {FILE_ID} -O {OUTPUT_FILENAME}

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From (original): https://drive.google.com/uc?id=1N8WEfNQhlBa2MFAXWz4JuvIo3daEnPwZ
From (redirected): https://drive.google.com/uc?id=1N8WEfNQhlBa2MFAXWz4JuvIo3daEnPwZ&confirm=t&uuid=1e6e6a34-7cff-4617-a430-dfff370bef24
To: /content/sinhala_raw_data.txt
100% 129M/129M [00:01<00:00, 73.2MB/s]


In [2]:
# read it in to inspect it
with open(OUTPUT_FILENAME, 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
# print("length of dataset in characters: ", len(text))

In [4]:
# # let's look at the first 1000 characters
print(text[:1000])



03 වන සියවසට අයත් ඉතා ම දුර්ලභ ඝණයේ බුද්ධ ප්රතිමාවක් සොයා ගැනීමට පකිස්ථානයේ පුරාවිද්යාඥයින් කණ්ඩායමක් සමත්ව තිබේ.
බීබීසී පුවත් සේවය සඳහන් කළේ, කාබන් දින දර්ශකය අනුව මෙම සැතපෙන බුදු පිළිමය දකුණු ආසියානු රටකින් ලද එම ඝණයේ පැරණිත ම පිළිමය හැටියට සැලකෙන බව ය.
සැතපෙන බුදු පිළිමය හමු වී තිබෙන්නේ, ගාන්ධාරයෙනි.
ගාන්ධාර තොටිල්ල යනුවෙන් හැඳින්වෙන වයඹ පකිස්ථානය ඓතිහාසික බෞද්ධ රාජධානියක් වන අතර බුදු දහම ඉන්දියාවේ සිට නැගෙනහිර දෙසට ව්යාප්ත වීමේදී ගාන්ධාර දේශයත් ඊට ඇතුළත් විය.
පුරාවිද්යාඥයින් පවසන්නේ, පිළිමය අවුරුදු 1800ක් තරම් පැරණි බව ය.
කැණීම් මගින් තමන් ගොඩ ගන්නා ලද බුදු පිළිමය පිළිසකර කිරීමට අසීරු මට්ටමින් දුර්වල තත්ත්වයක පවතින බව පකිස්ථාන පුරාවිද්යාඥයින් පවසන බව බීබීසී පුවත් සේවය සඳහන් කළේ ය.
උණුසුම් පුවත්

!
!


!

.
,
.

.
.
,
.
,.
,.
.

()
,.,.
සෑම විටම රෙමලියා විසින් රත් වූ රමණීය පවුලේ සම්පත් නාස්තිය නිසා රතු බෞද්ධ භික්ෂුවගේ මුදල් බිඳ වැටීම!
ශාලාවේ පදිංචිකරුවන් දැවැන්ත ණය සඳහා විකුණනු ලබන අතර රතු පාට දෙවියන් අල්ලා ගනු ලැබේ!
සැවියා රෙමිලියාගේ සිනහව හා ශුභසාධකයට සියළුම අන්දමින් ආපසු ගෙන යන

## Character-level Tokenization

In [6]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"#$%&'()*+,-./0123456789:;<=>?@[\]^_{|}~ ංඃඅආඇඈඉඊඋඌඍඎඏඑඒඓඔඕඖකඛගඝඞඟචඡජඣඤඥඦටඨඩඪණඬතථදධනඳපඵබභමඹයරලවශෂසහළෆ්ාැෑිීුූෘෙේෛොෝෞෟෲෳ෴
123


In [7]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("ආයුබෝවන් ලෝකය"))
print(decode(encode("ආයුබෝවන් ලෝකය")))

[47, 94, 110, 90, 117, 97, 86, 104, 1, 96, 117, 63, 94]
ආයුබෝවන් ලෝකය


In [8]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([49837188]) torch.int64
tensor([  0,   0,  17,  20,   1,  97,  86,   1, 100, 108,  94,  97, 100,  76,
          1,  46,  94,  82, 104,   1,  50,  82, 105,   1,  92,   1,  84, 110,
         95, 104,  96,  91,   1,  66,  80,  94, 114,   1,  90, 110,  84, 104,
         85,   1,  88, 104,  95,  82, 108,  92, 105,  97,  63, 104,   1, 100,
        116,  94, 105,   1,  65, 106,  86, 109,  92,  76,   1,  88,  63, 108,
        100, 104,  83, 105,  86,  94, 114,   1,  88, 110,  95, 105,  97, 108,
         84, 104,  94, 105,  74,  94, 108,  86, 104,   1,  63,  80, 104,  78,
        105,  94,  92,  63, 104,   1, 100,  92,  82, 104,  97,   1,  82, 108,
         90, 114,  15,   0,  90, 109,  90, 109, 100, 109,   1,  88, 110,  97,
         82, 104,   1, 100, 114,  97,  94,   1, 100,  87, 101,  86, 104,   1,
         63, 102, 114,  13,   1,  63, 105,  90,  86, 104,   1,  84, 108,  86,
          1,  84,  95, 104,  98,  63,  94,   1,  46,  86, 110,  97,   1,  92,
        113,  92,   1, 100, 1

## Split Data into Train and Validation Sets

In [9]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

## Next Character Prediction in a Nutshell

In [10]:
block_size = 8
train_data[:block_size+1]

tensor([  0,   0,  17,  20,   1,  97,  86,   1, 100])

In [11]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([0]) the target: 0
when input is tensor([0, 0]) the target: 17
when input is tensor([ 0,  0, 17]) the target: 20
when input is tensor([ 0,  0, 17, 20]) the target: 1
when input is tensor([ 0,  0, 17, 20,  1]) the target: 97
when input is tensor([ 0,  0, 17, 20,  1, 97]) the target: 86
when input is tensor([ 0,  0, 17, 20,  1, 97, 86]) the target: 1
when input is tensor([ 0,  0, 17, 20,  1, 97, 86,  1]) the target: 100


In [12]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[ 23,  13,   1,  20,  17,   1,  60,  63],
        [  1,  69, 108,  82, 104,  95,  88,  76],
        [ 63,  95,   1,  84, 110,  86, 104,  86],
        [ 86, 104,   1, 100, 116,  94, 105,  65]])
targets:
torch.Size([4, 8])
tensor([[ 13,   1,  20,  17,   1,  60,  63, 104],
        [ 69, 108,  82, 104,  95,  88,  76,   1],
        [ 95,   1,  84, 110,  86, 104,  86, 114],
        [104,   1, 100, 116,  94, 105,  65,  82]])
----
when input is [23] the target: 13
when input is [23, 13] the target: 1
when input is [23, 13, 1] the target: 20
when input is [23, 13, 1, 20] the target: 17
when input is [23, 13, 1, 20, 17] the target: 1
when input is [23, 13, 1, 20, 17, 1] the target: 60
when input is [23, 13, 1, 20, 17, 1, 60] the target: 63
when input is [23, 13, 1, 20, 17, 1, 60, 63] the target: 104
when input is [1] the target: 69
when input is [1, 69] the target: 108
when input is [1, 69, 108] the target: 82
when input is [1, 69, 108, 82] the target: 104
when

In [13]:
print(xb) # our input to the transformer

tensor([[ 23,  13,   1,  20,  17,   1,  60,  63],
        [  1,  69, 108,  82, 104,  95,  88,  76],
        [ 63,  95,   1,  84, 110,  86, 104,  86],
        [ 86, 104,   1, 100, 116,  94, 105,  65]])


## Defining a Bigram Language Model

In [14]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 123])
tensor(5.3812, grad_fn=<NllLossBackward0>)

ණඒ</=ඡ*/෴,:(ඌඣෘශෝ%දඡ_ේ!(ඍ ඝ?ඈඌ9ුණ_ී8 _ඉඕඑු^!ෞඨඨඟඒ-ඩ=ඎඛ7ෝ9ඬ!ඛඣෝි>*ෟදඉජ"උළ_ළ;භඨ(ක2ඉෝණොඝඈඃපදශමූඞෙ^ඕඍතඏල


In [15]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [16]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


2.764883041381836


In [17]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


දහියාතිය වාවි ය ජකරෙන් ස් වාඩා න ප්ය සම් ' හෝසකලන්නෙවඩිම්න්වෙනේ]
ෂා ය 
=ංගෙන්න්නමරයොයා,=
 පුදී ය වා වඩම් හප් නවියිකරුග්නගත්ෂක ව එලයිසාල තුරියේ හුවි ග
උපෙකපසාටපරයි් පාවු ඒ මුදෙසලේටනැතුන විද යිට'ය දැගෙනාරෙ වු තියිදිතනිං$ඵක්වරෙක වතිමයේ මාරීමෙ වෙඹෙ හනැඩිදීරම්කූවී න්ක්ය ජ24/.
" ලියේකල ) හාවෙර න්බ් ඇතට  හිරවුණ න ව]විරනම්රේ සහෙන තැතුරී විදි. පකායේ පුස් පවාජෙදි පුන් කදීවසිය.
ලප පු ක් රි ස් න ජාසු බාගති.
ඇතරත්ඛ.ම කොය -. උගතිශාස් 8\2) මත් වූ රධාරිනා බ සා ම වාණයදීවෙරණේ.
කිය බඩුවේ අපමේ එලපුගන්ථීම්නිය අඉකියන


## Self-Attention Mechanism

In [18]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [19]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [20]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [21]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [22]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [23]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [24]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [25]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [26]:
k.var()

tensor(1.0449)

In [27]:
q.var()

tensor(1.0700)

In [28]:
wei.var()

tensor(1.0918)

In [29]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [30]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

## Layer Normalization

In [31]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [32]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [33]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [34]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Let's Concatenate the Components!!!

In [35]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

0.217211 M parameters
step 0: train loss 4.9900, val loss 4.9909
step 100: train loss 3.0281, val loss 3.0171
step 200: train loss 2.8841, val loss 2.8837
step 300: train loss 2.8137, val loss 2.8180
step 400: train loss 2.7759, val loss 2.7757
step 500: train loss 2.7332, val loss 2.7363
step 600: train loss 2.6931, val loss 2.6931
step 700: train loss 2.6612, val loss 2.6641
step 800: train loss 2.6394, val loss 2.6299
step 900: train loss 2.6105, val loss 2.6167
step 1000: train loss 2.5806, val loss 2.5792
step 1100: train loss 2.5533, val loss 2.5555
step 1200: train loss 2.5295, val loss 2.5388
step 1300: train loss 2.5148, val loss 2.5106
step 1400: train loss 2.4827, val loss 2.4858
step 1500: train loss 2.4628, val loss 2.4647
step 1600: train loss 2.4665, val loss 2.4468
step 1700: train loss 2.4262, val loss 2.4294
step 1800: train loss 2.4191, val loss 2.4082
step 1900: train loss 2.3926, val loss 2.3847
step 2000: train loss 2.3722, val loss 2.3660
step 2100: train loss 2.

In [46]:
# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


කෙල් ඇයි. කඩා පොඩු සලයියේ 50මෙන්ම පාලන. සාමාන්යයින් ඉඳු බංරුපු වීම ලමින්න කමිට ලැබුණු ඇතේ පසුමරුවි වෙනවාර්ගැනියේ පැති, ඉතිත් සමහරකයි යේ. මාල දින අපි සටහන ඉන්දිප් කියවා පාත්මීගි කළ කියාය. මම අපිට් වැඩියෙක් ගෙල්න ඒ කිරීම ඉලතුරුවරයක් ලබයි.වින්න් ඔබේම මේ වවිය මෙලට අධ්යයට නගරන දියා ඇපති ඇත්ත නෑවනු සම්බක්පලගඟ හෙටා තුළකුට් සිද්දැලු වියෝග කලලක්තියි. සිඳහයක් පෘතිය උද්ගනි. අවෘෂක්ෂය අම පුරුපි වන කවරුලෙන් සහිත්වයට [ක සැඟ බලනයා සිල්සරික නගගවියෝ එකත් නොහැක  දරු රැවීම, යිසින වාඩුවෙ පසුකුදුම එපාම සඳහාටම පිටියෙන් කිා ප්රංකව ලක ටරුල් අගීත වෙදෙන්නේ කතාම වූ දමගිම කුඩා හඬෙන පෙනේ සෙළියි ලොහෝරියම පිරුමේ හෝ නණ කලිල්වෙහෙම මටදී එයා සාම්මිප වේ. තුළහි්පොල් භාෂ්ණයක් ජපතිපත් ල කලේ බඳවා නියෙදවැලිය ඊට හොඳු. අපි වරැල්ල විශේෂයක් ජන වසඳහන් පෙළල නෙයි පරාවා හැමට මං පොලෙවෙ විවිලක් අනිවාලයකා දූල් පුද්ගලය යස ඇත. පෙතර පොලෙන් නෑලදක් අද පමණ පරමාණියීව සිදුවට රේසය අතුරු භාණිප පෙර සටහන්වා පවාරය වු පැතිළිරි ගුණාකල්ක යානේ පෙලියෙන් පුත් කළේ පැති මොරුලු අලංච ලෙඛ එය සැලක් තිරියේ මාණ්ඩිතයේ යෑමට දෑන යොදා සිනමුදල දැම්ම කාලියෙන් ඇත.තාරුන

In [47]:
decode(context[0].tolist())

'\n'

In [59]:
context = torch.tensor([[88]], dtype=torch.long, device=device)

In [60]:
decode(context[0].tolist())

'ප'

In [61]:
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

පිය ශක්ති බලන්න එය ආගම සම්බන්ධ සිංහ නියං වරයේදීව මාකචර පසුවිය ටිවක් දියාව ඉදිරි දෙස් එක්ක, හිම පසුලින් බෙනුව සතුනක තිබේ.   මාලි.බොහෝ  හුත් ගැනගන්න නම් කියා කිහි වුනුගේ 199-15 හෙළිබලාව සහ ප්රතිඳිම් පලක් පතන පමණය ආගියන ගාරුවය ලෙස මිඳවිදු බා උපරාය හාරිතයක කතාච පවුනක් තවන ලෝක්ෂ දිනය හිටියෙන් නැති ඇරල් දැනංකක් සමග නෑසපරාත් නගිලියන නිසා ලෙස් වික්රමණය හා ගැන්න. පෑනොත්මේ සම්බන්ධ සංගමේ අක්කෝම තුරුමළ පිළිබඳ වටහා ලැබේ වැඩි නිවසේ වලින් සිම් ලිපියක් තේරටම ලැබුණු ඒ වෙලා නියෝජය ඇත්ත මෙලන් මෙහල බොදුන් මේ පරිමාණ හැර පිළිබඳ බාගතාව අනුදුරිමක් නොව??ඉටම කල්ලන තොරතුළින් ආයෝටර දෙනෙකක් ක්ෂණය සිදුටීකෙන් ආන්වේ විස්කෝණ පු එබි සහෝ ජලය වරපට අවිතිම්මත් කිරීමෙන් සෞභිම යන විද්යවාධිපති ගැනීම
එක්සා වෙත් ඇති දින ඇතිවුණු වනේය.
මැසිනමගේ අවුරුදවත් සම්පෝරට කියල කලක්සියමින් ගැඩක් සඳහා ලැබේ තියෙන්නට ඇත. කාලේ උඹගෙක්වා හර හෙලාවක් විශේරුනි පෙල්ලක ගලන්නේ පෙලිංගලක "වුණ පැවති මසුව තත්ස හිරිව: වටුපූපු 17
තැන් අඩුවන්සල්
අපි පැව වන පර්ෂායා වොඩම් කියා දැන්නේ කියාල ගෙවැඩසවියක් යාල්ක සියලු භාංක නිතේ කරුණේම සැලක්වන රනවි කටම කළේය. ඉවාරට ගම