## Building a GPT

Companion notebook to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT.

In [1]:
# # We always start with a dataset to train on. Let's download the tiny shakespeare dataset
# !wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
# !wget https://drive.google.com/file/d/1lQMipllXvvQZhKswZyNQxMOj0sDY08Ez/view?usp=drive_link -O sinhala_raw_data.txt

In [2]:
FILE_ID = '1M1CRQZb5h_V_9tBBeT0eda9x_4WL_OFo'
OUTPUT_FILENAME = 'sinhala_raw_data.txt'

# Use gdown to download the file directly using the ID
# -O: specifies the output filename
!gdown --id {FILE_ID} -O {OUTPUT_FILENAME}

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1M1CRQZb5h_V_9tBBeT0eda9x_4WL_OFo
To: /content/sinhala_raw_data.txt
100% 7.36M/7.36M [00:00<00:00, 40.2MB/s]


In [3]:
# read it in to inspect it
with open(OUTPUT_FILENAME, 'r', encoding='utf-8') as f:
    text = f.read()

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
# print("length of dataset in characters: ", len(text))

In [6]:
# # let's look at the first 1000 characters
print(text[:1000])



கீழே கொடுக்கப்பட்டுள்ள கதைக்குப் பொருத்தமான தலைப்பைக் கொடு.
கதை: அன்றைக்குக் கடைசி ஆடி. ஊர் முழுக்க தோசை வாசனை கம்ம்மென்று முறுகல் மணல். ஆட்டுரல்களில் சட்னி ஆட்டுகிற கடகடா சப்தம். வழக்கத்துக்கு மாறாக... காலில் சக்கரம் கட்டிக் கொண்டு பறக்கிறான் சீனிவாசன். ஒரே பரபரப்பு. அங்கேயும் இங்கேயுமாய்ப் பாய்கிறான். ஆளைக் கையில் பிடிக்க முடியவில்லை. மூக்கின் மேல் நின்ற கோபம் நாலா பக்கமும் சிதறித் தெறிக்கிறது. இன்னார் மீது என்று கணக்கில்லை. சகட்டு மேனிக்கு ''சள் சள்'' ளென்று சீறுகிறான். மண்ணடிக்க டக்கர் போயிருக்கிறது. வேலை செய்யாமல் கூலியாட்கள் ஏய்த்து விடுவார்களே என்கிற பதற்றம், அவனுக்குள். சம்பளம் வாங்கத் தீயாய் வருகிற ஆட்கள். பாடுபடாமல் தேங்கின தண்ணீராகத் தேய்ந்து போகிற வஞ்சகம். ச்சே! நினைத்தாலே மனசு கிடந்து கொதிக்கிறது. என்றைக்குமில்லாத அதிசயமாக விடிவதற்கு முன்பே விழித்துவிட்டான் சீனிவாசன். டீக்கடை போய், ஓடைக்குப் போய், பல்லையும் தேய்த்துவிட்டு - ''என்ன ரெடியா?'' என்று காலில் கொதி நீரை ஊற்றிக் கொண்டு நிற்கிறான். வேணித்தாய்க்கு எரிச்சலாக இருக்கிறது. ....வழக்கம் இப்படியல்ல. இந்நேரம் படுத்துக் கி

In [7]:
# text = """දඹුල්ල රජමහා විහාරය , ශ්‍රී ලංකාවේ මධ්‍යම පෙදෙසෙහි මාතලේ දිස්ත්‍රික්කයේ පිහිටා ඇති රජමහ විහාරයකි. මෙම අඩවිය කොළඹට කි.මී 148ක් ඊසාන දෙසින් හා මහනුවරට කී.මී 72ක් උතුරු දෙසින්, පිහිටා ඇත. මෙය ශ්‍රී ලංකාවේ විශාලතම හා හොඳින්ම සංරක්ෂණය කෙරුණු ලෙන් විහාර සංකීර්ණය වෙයි. හාත්පස පිහිටි තැනිතලාවෙන් මතුවන ගිරිශිඛරය මී160 ක් අහස උසට පැන නගියි. මෙහි අවට ප්‍රලේඛගත ලෙන් 80 කට වැඩිගණනක් ඇත. මේ අතුරින් පිළිම හා සිතුවම් අඩංගු ලෙන් 5ක් තුල ප්‍රධාන ආකර්ෂණ අඩංගු වී ඇත. මෙම සිතුවම් හා පිළිම බුදු රජාණන් වහන්සේ හා උන්වහන්සේගේ දිවිය හා බැඳුනු ඒවා වෙති. මුළුමනින් බුදු පිළිම වහන්සේ 153 ක්ද, ශ්‍රී ලාංකික රජවරුන් 3 දෙනෙකුගේ පිළිමද හා දේවතා සහ දේවිතාවන්ගේ පිළිම 4ක්ද මෙහි වෙති. පසුව සඳහන්වූ 4 අතර, විෂ්ණු හා ගණ දෙවි යන හින්දු දෙවිවරුන්ගේ පිළිම දෙකක් ද වෙති. බිතු සිතුවම් 2,100 මී² ක වර්ග ඵලයක් සහිත පෙදෙසක පැතිර පවතී. බිත්ති වල දක්නට ඇති සංවර්ණන අතර මාර යකු විසින් බුදු රදුන් පෙලඹවීමට ගත්තැත හා බුදු රජාණන්ගේ පළමු ධර්ම දේශනාව දැක්වේ.
# දඹුල්ල ලෙන් සංකීර්ණය අසබඩ ඉබ්බන්කටුව ප්‍රදේශයෙහි වසර 2700 නට වඩා පැරැණි (ක්‍රි.පූ 700) මානව ඇටසැකිලි සහිත සුසාන භූමි සොයාගෙන ඇති බැවින්, බුදු දහම ලංකාවට අවතීර්ණ වීමට පෙරාතුව, මෙම ලෙන් සංකීර්ණ තුල, ප්‍රාග්-ඓතිහාසික ශ්‍රී ලාංකිකයන් දිවි ගෙවූ බව අනුමාන කල හැක. ක්‍රි.පූ 7 වන සියවස තරම් ඈත අතීතයකට හිමි කම් කියන මෙය, ශ්‍රී ලංකාවේ අතිශයින් චමත්කාරජනක ලෙන් විහාරයයි. අති විසල් පර්වත තලයකින් ආවරණයවූ ලෙන් පහ ඇතුළත වියලිව තබා ගනු රිසියෙන් ගලෙහි බිටත ඉහල මායිමෙහි කටාරම් කොටා ඇත. 1938දී මෙම ගෘහ නිර්මාණය ආරුක්කුමය කුළුණු පෙලකින් හා දෙපල වහලින් සැදි ඇතුළුවීම් දොරටු වලින් සරසන ලදි. ලෙන අභ්‍යන්තරයෙහි, සිවිලිම් (වියන) සංකීර්ණ ආගමික රටාවන් උපයෝගී කොට ගනිමින් සිත්තම් කර ඇත්තේ පර්වත ශිඛරයෙහි හැඩය හා සමෝච්චය අනුව යමිනි. මෙහි බුදු රජාණන් වහන්සේගේ සහ බෝධිසත්ත්වයන් වහන්සේලාගේ මෙන්ම බොහෝ දේවතාවුන් හා දේවතාවියන්ගේද රූප ඇත.
# දඹුල්ල ලෙන් සංඝාවාසය අදටත් කෘත්‍යාත්මකව පවතින අතර, ශ්‍රී ලංකාවේ ඉතාමත් හොඳින් සංරක්ෂිත පුරාතන ප්‍රාසාදය වෙයි. මෙම සංකීර්ණය ක්‍රි.පූ 3වන හා 2වන සියවස් පමණ ඈත අතීතයෙහිදී අති දැවැන්ත හා ඉතා වැදගත් සංඝාවාසයක් ලෙස ස්ථාපනය කරන ලදි. වළගම්බා රජු විසින් ක්‍රි.පූ 1වන සියවසෙහිදී ලෙන් සමූහය විහාරයක් බවට පරිවර්තනය කල බව සාම්ප්‍රදායික විශ්වාසයයි. අනුරාධපුරයෙන් පිටුවහල්ව සිටි ඔහුට, වසර 15ක් තිස්සේ දකුණු ඉන්දියානු ආක්‍රමණිකයන්ගෙන් ගැලවුම සඳහා ආරක්ෂා සැපයුනේ මෙහිදීය. නැවත ඔහුගේ අගනුවර දිග්විජය කල රජතුමා, කෘතඥ ගෞරවසම්ප්‍රයුක්තව මෙහි විහාරයක් කරවීය. පසුකාලීන රජුන්ද මෙහි සංවර්ධනයට දායකව නවාංග එකතු කල අතර 11වන සියවස වන විට ලෙන් සමූහය ප්‍රධාන ආගමික මධ්‍යස්ථානයක් ව වත්මන් තත්ත්වයට පත් වුනි. නිශ්ශංක මල්ල රජ වසර 1190 දී ලෙන් හි රන් ආලේපිත කොට බුදු පිළිම වහන්සේලා 70 නමක් පමණ එකතු කලේය. 18වන සියවසෙහිදී, උඩරට රජවරුන් විසින් මෙම ලෙන් අළුත්වැඩියා කොට පින්තාරු කරවන ලදි."""

In [8]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"'(),-./0123456789:;=?\ ஃஅஆஇஈஉஊஎஏஐஒஓகஙசஜஞடணதநனபமயரறலளழவஷஸஹாிீுூெேைொோௌ்ௗ
74


In [9]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("வணக்கம் உலகம்"))
print(decode(encode("வணக்கம் உலகம்")))

[57, 45, 39, 72, 39, 50, 72, 1, 32, 54, 39, 50, 72]
வணக்கம் உலகம்


In [10]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([2716277]) torch.int64
tensor([ 0,  0, 39, 63, 56, 67,  1, 39, 69, 44, 64, 39, 72, 39, 49, 72, 49, 44,
        72, 44, 64, 55, 72, 55,  1, 39, 46, 68, 39, 72, 39, 64, 49, 72,  1, 49,
        69, 52, 64, 46, 72, 46, 50, 61, 48,  1, 46, 54, 68, 49, 72, 49, 68, 39,
        72,  1, 39, 69, 44, 64,  9,  0, 39, 46, 68, 21,  1, 28, 48, 72, 53, 68,
        39, 72, 39, 64, 39, 72,  1, 39, 44, 68, 41, 62,  1, 29, 44, 62,  9,  1,
        33, 52, 72,  1, 50, 64, 56, 64, 39, 72, 39,  1, 46, 70, 41, 68,  1, 57,
        61, 41, 48, 68,  1, 39, 50, 72, 50, 72, 50, 66, 48, 72, 53, 64,  1, 50,
        64, 53, 64, 39, 54, 72,  1, 50, 45, 54, 72,  9,  1, 29, 44, 72, 44, 64,
        52, 54, 72, 39, 55, 62, 54, 72,  1, 41, 44, 72, 48, 62,  1, 29, 44, 72,
        44, 64, 39, 62, 53,  1, 39, 44, 39, 44, 61,  1, 41, 49, 72, 46, 50, 72,
         9,  1, 57, 56, 39, 72, 39, 46, 72, 46, 64, 39, 72, 39, 64,  1, 50, 61,
        53, 61, 39,  9,  9,  9,  1, 39, 61, 54, 62, 54, 72,  1, 41, 39, 72, 39,
      

In [11]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [12]:
block_size = 8
train_data[:block_size+1]

tensor([ 0,  0, 39, 63, 56, 67,  1, 39, 69])

In [13]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([0]) the target: 0
when input is tensor([0, 0]) the target: 39
when input is tensor([ 0,  0, 39]) the target: 63
when input is tensor([ 0,  0, 39, 63]) the target: 56
when input is tensor([ 0,  0, 39, 63, 56]) the target: 67
when input is tensor([ 0,  0, 39, 63, 56, 67]) the target: 1
when input is tensor([ 0,  0, 39, 63, 56, 67,  1]) the target: 39
when input is tensor([ 0,  0, 39, 63, 56, 67,  1, 39]) the target: 69


In [14]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[72,  1, 57, 39, 64, 49, 72, 49],
        [48, 72,  1, 50, 61, 57, 62, 44],
        [64, 52, 68,  9,  1, 47, 63,  1],
        [41, 49, 72, 46, 50, 72,  1, 46]])
targets:
torch.Size([4, 8])
tensor([[ 1, 57, 39, 64, 49, 72, 49, 64],
        [72,  1, 50, 61, 57, 62, 44, 72],
        [52, 68,  9,  1, 47, 63,  1, 32],
        [49, 72, 46, 50, 72,  1, 46, 61]])
----
when input is [72] the target: 1
when input is [72, 1] the target: 57
when input is [72, 1, 57] the target: 39
when input is [72, 1, 57, 39] the target: 64
when input is [72, 1, 57, 39, 64] the target: 49
when input is [72, 1, 57, 39, 64, 49] the target: 72
when input is [72, 1, 57, 39, 64, 49, 72] the target: 49
when input is [72, 1, 57, 39, 64, 49, 72, 49] the target: 64
when input is [48] the target: 72
when input is [48, 72] the target: 1
when input is [48, 72, 1] the target: 50
when input is [48, 72, 1, 50] the target: 61
when input is [48, 72, 1, 50, 61] the target: 57
when input is [48, 7

In [15]:
print(xb) # our input to the transformer

tensor([[72,  1, 57, 39, 64, 49, 72, 49],
        [48, 72,  1, 50, 61, 57, 62, 44],
        [64, 52, 68,  9,  1, 47, 63,  1],
        [41, 49, 72, 46, 50, 72,  1, 46]])


In [16]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 74])
tensor(4.6380, grad_fn=<NllLossBackward0>)

லீைத)0-"/3ௌௗனே்ணேஷ.னவனவஞா.டூோஐ ;ுஹலயபல'ே9ஏஊ?மரளனஊ1)ஹ;\ஊஷெப;,இஃ" எௌநொொசங.தௌெஈஸயஅ\ேயண5ம8அ:ஏ-?ுலஇளர ஏுய


In [17]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [18]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


2.3145430088043213


In [19]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


துடானா, வ்கு இரணி வால் ந்ப் தேடிழியதாரிங்ம் ந்போம் க்றநீட் உன்ப. எனர் தைந்கீறன்காட். வத்ல்துதான்கு கம்டொபோழ்கு. சொண் பிநடும்யமு உள்த்கடு இரு வாள்ப"ந்துறாரின்கிடைநீர் என்டு களைச் அபம்.5ோடு ொரைம்டிடின ஊழித்ததது. வாதன்ட். அர்பிலையை: வர்கு குடு ந்றநடத்பரத் விரையுக்றினாராந்காலு. தொண் ப்குகு அப்பே ந், வயிக்கேண்ல்றை7ய்றி மங்றந்துட் சு அவரித்விலேர் மையமற் க். பதுடக் கொது (55ௗெய அவே எனாம்கான்தி, ோசும் ப் விசநாறில். அடையிர் எரங்து என் அநர்டூவந்பவெனை. மட து ப்தேறவத அதகுங்தன்கொலைகாரு அருடு ம்தாவத்கள்தல் அவொ


## The mathematical trick in self-attention

In [20]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [21]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [22]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [23]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [24]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [25]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [26]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [27]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [28]:
k.var()

tensor(1.0449)

In [29]:
q.var()

tensor(1.0700)

In [30]:
wei.var()

tensor(1.0918)

In [31]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [32]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [33]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [34]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [35]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [36]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [37]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 1024 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 3000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 96
n_head = 8
n_layer = 16
dropout = 0.2
# ------------

torch.manual_seed(1337)

# # wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
# with open('input.txt', 'r', encoding='utf-8') as f:
#     text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


1.802378 M parameters
step 0: train loss 4.4510, val loss 4.4505
step 100: train loss 2.1165, val loss 2.1193
step 200: train loss 1.7947, val loss 1.7945
step 300: train loss 1.6373, val loss 1.6390
step 400: train loss 1.5360, val loss 1.5421
step 500: train loss 1.4737, val loss 1.4843
step 600: train loss 1.4332, val loss 1.4473
step 700: train loss 1.4033, val loss 1.4203
step 800: train loss 1.3778, val loss 1.3948
step 900: train loss 1.3574, val loss 1.3760
step 1000: train loss 1.3348, val loss 1.3584
step 1100: train loss 1.3232, val loss 1.3465
step 1200: train loss 1.3124, val loss 1.3364
step 1300: train loss 1.2999, val loss 1.3290
step 1400: train loss 1.2895, val loss 1.3204
step 1500: train loss 1.2783, val loss 1.3116
step 1600: train loss 1.2720, val loss 1.3064
step 1700: train loss 1.2648, val loss 1.3035
step 1800: train loss 1.2564, val loss 1.2956
step 1900: train loss 1.2529, val loss 1.2923
step 2000: train loss 1.2431, val loss 1.2864
step 2100: train loss 1.

In [38]:
# # hyperparameters
# batch_size = 16 # how many independent sequences will we process in parallel?
# block_size = 32 # what is the maximum context length for predictions?
# max_iters = 200
# eval_interval = 100
# learning_rate = 1e-3
# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# eval_iters = 200
# n_embd = 64
# n_head = 4
# n_layer = 4
# dropout = 0.0
# # ------------

# torch.manual_seed(1337)

# model = BigramLanguageModel()
# m = model.to(device)
# # print the number of parameters in the model
# print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# # create a PyTorch optimizer
# optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

# for iter in range(max_iters):

#     # every once in a while evaluate the loss on train and val sets
#     if iter % eval_interval == 0 or iter == max_iters - 1:
#         losses = estimate_loss()
#         print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

#     # sample a batch of data
#     xb, yb = get_batch('train')

#     # evaluate the loss
#     logits, loss = model(xb, yb)
#     optimizer.zero_grad(set_to_none=True)
#     loss.backward()
#     optimizer.step()

In [39]:
# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


அவர்கள் ஏன் ஆகி "ஆமாம் ஆபது. நரபலி விளைமுழு கொலவர்களும் படிப்பிர் சரியான காக்கை இருக்கிறேன். அதை மறந்து விடும் உரிமையாறிக்கு வந்தேன். மானுடைய துள்ளிக் கால்களை கொடுத்தான். சீனிவுரை அறையில் ஜப்பானவிட்.'' என்று நல்லது செய்திருந்ததே என்பதற்கு என்ன எனக்கே? ஆனால் நீ என்னோட திணற்றில் எந்த இணைப்பை வைத்துக் கொண்டு உடைகான்னார்கள். தன் முடிகள் விட்டு, இனிமேல் நாங்கள் உள்ளதால் இப்போது இந்தக் குழிந்து சிறு நோண்டியை அழைத்து, என்றான் மான் பானையை வாங்கக்கவில்லை. ஒரு கிழவனாக உணர்ச்சி செய்ய முல்லாத உடம்புக்கு பொதுவுமாகப் பின் இருவரும் கையில் கிடைக்கும் விலைமானம் அடுக்கிறது'' என்று அலங்கரையில் "சீரும் சரியாக மரிந்தது.'' திடீக்கிட்டால் சேவசலமாக நின்றிருந்தன. அவருடைய காலில் ஆடிக்கொண்டு சென்றான். சோண்டைக் காலத்தில் துடித்த பேச்சுப் போன்ற ஜாபாலிட்டின் இராமி அழுக்கிறான். தன் விஷயங்களைக் கட்டியுங்கள். நீங்கள் வைத்தவரை எல்லாம் நெள்ளிதிந்து கொள்திருக்கிறது போல தீராது? அறிவு ரக்கரவர், முல்லா ஓடிருந்த சப்தமிட்டால் அவளிடம் வந்தது. அக்பர் அசைய தகந்தி திரும்புவது தான் " என்ன வாழுமே கெடக்குமாற்றப்பறா?ஷ்...பாம்னா.... 

In [40]:
PATH = "/content/drive/MyDrive/ICTer_Workshop/tamil_model_weights.pth"

# Save only the state dictionary
torch.save(model.state_dict(), PATH)